[package]
name = "diem-json-rpc-types"
version = "0.0.3"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem JSONRPC Types"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[dependencies]
anyhow = "1.0.52"
hex = "0.4.3"
serde = { version = "1.0.124", default-features = false }
serde_json = "1.0.64"

bcs = "0.1.2"
diem-crypto = { path = "../../crates/diem-crypto", version = "0.0.3"  }
diem-transaction-builder = { path = "../../sdk/transaction-builder", version = "0.0.3" }
diem-types = { path = "../../types", version = "0.0.3" }
move-core-types = { git = "https://github.com/diem/move", rev = "98ed299a7e3a9223019c9bdf4dd92fea9faef860", version = "0.0.3"  }
num-derive = "0.3.3"
num-traits = "0.2.14"
thiserror = "1.0.24"
diem-workspace-hack = { version = "0.1", path = "../../crates/diem-workspace-hack" }
