[package]
name = "diem-workspace-hack"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem workspace hack"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

### BEGIN HAKARI SECTION
[dependencies]
Inflector = { version = "0.11.4", features = ["heavyweight", "lazy_static", "regex"] }
anyhow = { version = "1.0.52", features = ["backtrace", "std"] }
backtrace = { version = "0.3.56", features = ["addr2line", "gimli-symbolize", "miniz_oxide", "object", "serde", "std"] }
bitvec = { version = "0.19.5", features = ["alloc", "atomic", "std"] }
byteorder = { version = "1.4.3", features = ["i128", "std"] }
bytes = { version = "1.0.1", features = ["serde", "std"] }
chrono = { version = "0.4.19", features = ["clock", "libc", "oldtime", "serde", "std", "time", "winapi"] }
clap = { version = "2.33.3", features = ["ansi_term", "atty", "color", "strsim", "suggestions", "vec_map"] }
crossbeam-channel = { version = "0.5.1", features = ["crossbeam-utils", "std"] }
crossbeam-deque = { version = "0.8.1", features = ["crossbeam-epoch", "crossbeam-utils", "std"] }
crossbeam-queue = { version = "0.3.1", features = ["alloc", "std"] }
crossbeam-utils = { version = "0.8.3", features = ["lazy_static", "std"] }
either = { version = "1.6.1", features = ["use_std"] }
futures = { version = "0.3.12", features = ["alloc", "async-await", "executor", "futures-executor", "std"] }
futures-channel = { version = "0.3.16", features = ["alloc", "futures-sink", "sink", "std"] }
futures-core = { version = "0.3.16", features = ["alloc", "std"] }
futures-io = { version = "0.3.16", features = ["std"] }
futures-sink = { version = "0.3.16", features = ["alloc", "std"] }
futures-util = { version = "0.3.16", features = ["alloc", "async-await", "async-await-macro", "channel", "futures-channel", "futures-io", "futures-macro", "futures-sink", "io", "memchr", "proc-macro-hack", "proc-macro-nested", "sink", "slab", "std"] }
hyper = { version = "0.14.11", features = ["client", "full", "h2", "http1", "http2", "runtime", "server", "socket2", "stream", "tcp"] }
indexmap = { version = "1.7.0", default-features = false, features = ["std"] }
itertools = { version = "0.10.1", features = ["use_alloc", "use_std"] }
libc = { version = "0.2.112", features = ["std"] }
log = { version = "0.4.14", default-features = false, features = ["serde", "std"] }
memchr = { version = "2.4.0", features = ["std", "use_std"] }
num-integer = { version = "0.1.44", default-features = false, features = ["i128", "std"] }
num-traits = { version = "0.2.14", features = ["i128", "std"] }
plotters = { version = "0.3.0", default-features = false, features = ["area_series", "evcxr", "histogram", "line_series", "plotters-svg", "svg_backend"] }
rand = { version = "0.8.4", features = ["alloc", "getrandom", "libc", "rand_chacha", "rand_hc", "small_rng", "std", "std_rng"] }
regex = { version = "1.4.3", features = ["aho-corasick", "memchr", "perf", "perf-cache", "perf-dfa", "perf-inline", "perf-literal", "std", "thread_local", "unicode", "unicode-age", "unicode-bool", "unicode-case", "unicode-gencat", "unicode-perl", "unicode-script", "unicode-segment"] }
regex-automata = { version = "0.1.9", features = ["regex-syntax", "std"] }
reqwest = { version = "0.11.2", features = ["__tls", "blocking", "default-tls", "hyper-tls", "json", "native-tls-crate", "serde_json", "stream", "tokio-native-tls"] }
rusty-fork = { version = "0.3.0", features = ["timeout", "wait-timeout"] }
serde = { version = "1.0.130", features = ["alloc", "derive", "rc", "serde_derive", "std"] }
serde_json = { version = "1.0.73", features = ["indexmap", "preserve_order", "std"] }
standback = { version = "0.2.15", default-features = false, features = ["std"] }
subtle = { version = "2.4.0", default-features = false, features = ["std"] }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
tokio = { version = "1.9.0", features = ["bytes", "fs", "full", "io-std", "io-util", "libc", "macros", "memchr", "mio", "net", "num_cpus", "once_cell", "parking_lot", "process", "rt", "rt-multi-thread", "signal", "signal-hook-registry", "sync", "test-util", "time", "tokio-macros", "winapi"] }
tokio-util = { version = "0.6.7", features = ["codec", "compat", "futures-io", "io"] }
toml = { version = "0.5.8" }
tracing = { version = "0.1.26", features = ["attributes", "log", "std", "tracing-attributes"] }
url = { version = "2.2.2", default-features = false, features = ["serde"] }
warp = { version = "0.3.0", features = ["multipart", "tls", "tokio-rustls", "tokio-tungstenite", "websocket"] }
zeroize = { version = "1.2.0", features = ["alloc", "zeroize_derive"] }

[build-dependencies]
Inflector = { version = "0.11.4", features = ["heavyweight", "lazy_static", "regex"] }
anyhow = { version = "1.0.52", features = ["backtrace", "std"] }
backtrace = { version = "0.3.56", features = ["addr2line", "gimli-symbolize", "miniz_oxide", "object", "serde", "std"] }
bitvec = { version = "0.19.5", features = ["alloc", "atomic", "std"] }
byteorder = { version = "1.4.3", features = ["i128", "std"] }
bytes = { version = "1.0.1", features = ["serde", "std"] }
cc = { version = "1.0.67", default-features = false, features = ["jobserver", "parallel"] }
chrono = { version = "0.4.19", features = ["clock", "libc", "oldtime", "serde", "std", "time", "winapi"] }
clap = { version = "2.33.3", features = ["ansi_term", "atty", "color", "strsim", "suggestions", "vec_map"] }
crossbeam-channel = { version = "0.5.1", features = ["crossbeam-utils", "std"] }
crossbeam-deque = { version = "0.8.1", features = ["crossbeam-epoch", "crossbeam-utils", "std"] }
crossbeam-queue = { version = "0.3.1", features = ["alloc", "std"] }
crossbeam-utils = { version = "0.8.3", features = ["lazy_static", "std"] }
either = { version = "1.6.1", features = ["use_std"] }
futures = { version = "0.3.12", features = ["alloc", "async-await", "executor", "futures-executor", "std"] }
futures-channel = { version = "0.3.16", features = ["alloc", "futures-sink", "sink", "std"] }
futures-core = { version = "0.3.16", features = ["alloc", "std"] }
futures-io = { version = "0.3.16", features = ["std"] }
futures-sink = { version = "0.3.16", features = ["alloc", "std"] }
futures-util = { version = "0.3.16", features = ["alloc", "async-await", "async-await-macro", "channel", "futures-channel", "futures-io", "futures-macro", "futures-sink", "io", "memchr", "proc-macro-hack", "proc-macro-nested", "sink", "slab", "std"] }
hyper = { version = "0.14.11", features = ["client", "full", "h2", "http1", "http2", "runtime", "server", "socket2", "stream", "tcp"] }
indexmap = { version = "1.7.0", default-features = false, features = ["std"] }
itertools = { version = "0.10.1", features = ["use_alloc", "use_std"] }
libc = { version = "0.2.112", features = ["std"] }
log = { version = "0.4.14", default-features = false, features = ["serde", "std"] }
memchr = { version = "2.4.0", features = ["std", "use_std"] }
num-integer = { version = "0.1.44", default-features = false, features = ["i128", "std"] }
num-traits = { version = "0.2.14", features = ["i128", "std"] }
plotters = { version = "0.3.0", default-features = false, features = ["area_series", "evcxr", "histogram", "line_series", "plotters-svg", "svg_backend"] }
rand = { version = "0.8.4", features = ["alloc", "getrandom", "libc", "rand_chacha", "rand_hc", "small_rng", "std", "std_rng"] }
regex = { version = "1.4.3", features = ["aho-corasick", "memchr", "perf", "perf-cache", "perf-dfa", "perf-inline", "perf-literal", "std", "thread_local", "unicode", "unicode-age", "unicode-bool", "unicode-case", "unicode-gencat", "unicode-perl", "unicode-script", "unicode-segment"] }
regex-automata = { version = "0.1.9", features = ["regex-syntax", "std"] }
reqwest = { version = "0.11.2", features = ["__tls", "blocking", "default-tls", "hyper-tls", "json", "native-tls-crate", "serde_json", "stream", "tokio-native-tls"] }
rusty-fork = { version = "0.3.0", features = ["timeout", "wait-timeout"] }
serde = { version = "1.0.130", features = ["alloc", "derive", "rc", "serde_derive", "std"] }
serde_json = { version = "1.0.73", features = ["indexmap", "preserve_order", "std"] }
standback = { version = "0.2.15", default-features = false, features = ["std"] }
subtle = { version = "2.4.0", default-features = false, features = ["std"] }
syn = { version = "1.0.74", features = ["clone-impls", "derive", "extra-traits", "full", "parsing", "printing", "proc-macro", "quote", "visit", "visit-mut"] }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
tokio = { version = "1.9.0", features = ["bytes", "fs", "full", "io-std", "io-util", "libc", "macros", "memchr", "mio", "net", "num_cpus", "once_cell", "parking_lot", "process", "rt", "rt-multi-thread", "signal", "signal-hook-registry", "sync", "test-util", "time", "tokio-macros", "winapi"] }
tokio-util = { version = "0.6.7", features = ["codec", "compat", "futures-io", "io"] }
toml = { version = "0.5.8" }
tracing = { version = "0.1.26", features = ["attributes", "log", "std", "tracing-attributes"] }
url = { version = "2.2.2", default-features = false, features = ["serde"] }
warp = { version = "0.3.0", features = ["multipart", "tls", "tokio-rustls", "tokio-tungstenite", "websocket"] }
zeroize = { version = "1.2.0", features = ["alloc", "zeroize_derive"] }

### END HAKARI SECTION
